{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: Google-Images-Search in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (1.3.8)\n",
      "Requirement already satisfied: colorama~=0.4 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from Google-Images-Search) (0.4.4)\n",
      "Requirement already satisfied: pyfiglet~=0.8 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from Google-Images-Search) (0.8.post1)\n",
      "Requirement already satisfied: six~=1.12 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from Google-Images-Search) (1.15.0)\n",
      "Requirement already satisfied: click~=7.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from Google-Images-Search) (7.1.2)\n",
      "Requirement already satisfied: Pillow>=8.1.1 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from Google-Images-Search) (8.2.0)\n",
      "Requirement already satisfied: python-resize-image~=1.1 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from Google-Images-Search) (1.1.19)\n",
      "Collecting google-api-python-client~=1.7\n",
      "  Using cached google_api_python_client-1.12.8-py2.py3-none-any.whl (61 kB)\n",
      "Requirement already satisfied: requests~=2.21 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from Google-Images-Search) (2.24.0)\n",
      "Requirement already satisfied: termcolor~=1.1 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from Google-Images-Search) (1.1.0)\n",
      "Requirement already satisfied: google-api-core<2dev,>=1.21.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client~=1.7->Google-Images-Search) (1.26.3)\n",
      "Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client~=1.7->Google-Images-Search) (3.0.1)\n",
      "Requirement already satisfied: httplib2<1dev,>=0.15.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client~=1.7->Google-Images-Search) (0.19.1)\n",
      "Requirement already satisfied: google-auth>=1.16.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client~=1.7->Google-Images-Search) (1.29.0)\n",
      "Requirement already satisfied: google-auth-httplib2>=0.0.3 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client~=1.7->Google-Images-Search) (0.1.0)\n",
      "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests~=2.21->Google-Images-Search) (1.25.11)\n",
      "Requirement already satisfied: idna<3,>=2.5 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests~=2.21->Google-Images-Search) (2.10)\n",
      "Requirement already satisfied: chardet<4,>=3.0.2 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests~=2.21->Google-Images-Search) (3.0.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests~=2.21->Google-Images-Search) (2020.6.20)\n",
      "Requirement already satisfied: protobuf>=3.12.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client~=1.7->Google-Images-Search) (3.15.8)\n",
      "Requirement already satisfied: setuptools>=40.3.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client~=1.7->Google-Images-Search) (50.3.1.post20201107)\n",
      "Requirement already satisfied: packaging>=14.3 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client~=1.7->Google-Images-Search) (20.4)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client~=1.7->Google-Images-Search) (1.53.0)\n",
      "Requirement already satisfied: pytz in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client~=1.7->Google-Images-Search) (2020.1)\n",
      "Requirement already satisfied: pyparsing<3,>=2.4.2 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client~=1.7->Google-Images-Search) (2.4.7)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth>=1.16.0->google-api-python-client~=1.7->Google-Images-Search) (0.2.8)\n",
      "Requirement already satisfied: cachetools<5.0,>=2.0.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth>=1.16.0->google-api-python-client~=1.7->Google-Images-Search) (4.2.1)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4; python_version >= \"3.6\" in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth>=1.16.0->google-api-python-client~=1.7->Google-Images-Search) (4.7.2)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.16.0->google-api-python-client~=1.7->Google-Images-Search) (0.4.8)\n",
      "Installing collected packages: google-api-python-client\n",
      "  Attempting uninstall: google-api-python-client\n",
      "    Found existing installation: google-api-python-client 2.6.0\n",
      "    Uninstalling google-api-python-client-2.6.0:\n",
      "      Successfully uninstalled google-api-python-client-2.6.0\n",
      "Successfully installed google-api-python-client-1.12.8\n",
      "Collecting google-api-python-client\n",
      "  Using cached google_api_python_client-2.6.0-py2.py3-none-any.whl (7.2 MB)\n",
      "Requirement already up-to-date: google-auth-httplib2 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (0.1.0)\n",
      "Requirement already up-to-date: google-auth-oauthlib in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (0.4.4)\n",
      "Requirement already satisfied, skipping upgrade: six<2dev,>=1.13.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client) (1.15.0)\n",
      "Requirement already satisfied, skipping upgrade: uritemplate<4dev,>=3.0.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client) (3.0.1)\n",
      "Requirement already satisfied, skipping upgrade: google-auth<2dev,>=1.16.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client) (1.29.0)\n",
      "Requirement already satisfied, skipping upgrade: google-api-core<2dev,>=1.21.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client) (1.26.3)\n",
      "Requirement already satisfied, skipping upgrade: httplib2<1dev,>=0.15.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client) (0.19.1)\n",
      "Requirement already satisfied, skipping upgrade: requests-oauthlib>=0.7.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth-oauthlib) (1.3.0)\n",
      "Requirement already satisfied, skipping upgrade: setuptools>=40.3.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth<2dev,>=1.16.0->google-api-python-client) (50.3.1.post20201107)\n",
      "Requirement already satisfied, skipping upgrade: cachetools<5.0,>=2.0.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth<2dev,>=1.16.0->google-api-python-client) (4.2.1)\n",
      "Requirement already satisfied, skipping upgrade: rsa<5,>=3.1.4; python_version >= \"3.6\" in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth<2dev,>=1.16.0->google-api-python-client) (4.7.2)\n",
      "Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth<2dev,>=1.16.0->google-api-python-client) (0.2.8)\n",
      "Requirement already satisfied, skipping upgrade: requests<3.0.0dev,>=2.18.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client) (2.24.0)\n",
      "Requirement already satisfied, skipping upgrade: packaging>=14.3 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client) (20.4)\n",
      "Requirement already satisfied, skipping upgrade: pytz in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client) (2020.1)\n",
      "Requirement already satisfied, skipping upgrade: protobuf>=3.12.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client) (3.15.8)\n",
      "Requirement already satisfied, skipping upgrade: googleapis-common-protos<2.0dev,>=1.6.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client) (1.53.0)\n",
      "Requirement already satisfied, skipping upgrade: pyparsing<3,>=2.4.2 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client) (2.4.7)\n",
      "Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.1.0)\n",
      "Requirement already satisfied, skipping upgrade: pyasn1>=0.1.3 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from rsa<5,>=3.1.4; python_version >= \"3.6\"->google-auth<2dev,>=1.16.0->google-api-python-client) (0.4.8)\n",
      "Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.21.0->google-api-python-client) (1.25.11)\n",
      "Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.21.0->google-api-python-client) (2020.6.20)\n",
      "Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.21.0->google-api-python-client) (3.0.4)\n",
      "Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.21.0->google-api-python-client) (2.10)\n",
      "Installing collected packages: google-api-python-client\n",
      "  Attempting uninstall: google-api-python-client\n",
      "    Found existing installation: google-api-python-client 1.12.8\n",
      "    Uninstalling google-api-python-client-1.12.8:\n",
      "      Successfully uninstalled google-api-python-client-1.12.8\n",
      "\u001b[31mERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.\n",
      "\n",
      "We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.\n",
      "\n",
      "google-images-search 1.3.8 requires google-api-python-client~=1.7, but you'll have google-api-python-client 2.6.0 which is incompatible.\u001b[0m\n",
      "Successfully installed google-api-python-client-2.6.0\n",
      "Requirement already satisfied: pydrive in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (1.3.1)\n",
      "Requirement already satisfied: PyYAML>=3.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from pydrive) (5.3.1)\n",
      "Requirement already satisfied: oauth2client>=4.0.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from pydrive) (4.1.3)\n",
      "Requirement already satisfied: google-api-python-client>=1.2 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from pydrive) (2.6.0)\n",
      "Requirement already satisfied: pyasn1>=0.1.7 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from oauth2client>=4.0.0->pydrive) (0.4.8)\n",
      "Requirement already satisfied: six>=1.6.1 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from oauth2client>=4.0.0->pydrive) (1.15.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.0.5 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from oauth2client>=4.0.0->pydrive) (0.2.8)\n",
      "Requirement already satisfied: rsa>=3.1.4 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from oauth2client>=4.0.0->pydrive) (4.7.2)\n",
      "Requirement already satisfied: httplib2>=0.9.1 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from oauth2client>=4.0.0->pydrive) (0.19.1)\n",
      "Requirement already satisfied: google-auth-httplib2>=0.1.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client>=1.2->pydrive) (0.1.0)\n",
      "Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client>=1.2->pydrive) (3.0.1)\n",
      "Requirement already satisfied: google-api-core<2dev,>=1.21.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client>=1.2->pydrive) (1.26.3)\n",
      "Requirement already satisfied: google-auth<2dev,>=1.16.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client>=1.2->pydrive) (1.29.0)\n",
      "Requirement already satisfied: pyparsing<3,>=2.4.2 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from httplib2>=0.9.1->oauth2client>=4.0.0->pydrive) (2.4.7)\n",
      "Requirement already satisfied: setuptools>=40.3.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client>=1.2->pydrive) (50.3.1.post20201107)\n",
      "Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client>=1.2->pydrive) (2.24.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client>=1.2->pydrive) (1.53.0)\n",
      "Requirement already satisfied: packaging>=14.3 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client>=1.2->pydrive) (20.4)\n",
      "Requirement already satisfied: pytz in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client>=1.2->pydrive) (2020.1)\n",
      "Requirement already satisfied: protobuf>=3.12.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client>=1.2->pydrive) (3.15.8)\n",
      "Requirement already satisfied: cachetools<5.0,>=2.0.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth<2dev,>=1.16.0->google-api-python-client>=1.2->pydrive) (4.2.1)\n",
      "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.21.0->google-api-python-client>=1.2->pydrive) (1.25.11)\n",
      "Requirement already satisfied: idna<3,>=2.5 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.21.0->google-api-python-client>=1.2->pydrive) (2.10)\n",
      "Requirement already satisfied: chardet<4,>=3.0.2 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.21.0->google-api-python-client>=1.2->pydrive) (3.0.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.21.0->google-api-python-client>=1.2->pydrive) (2020.6.20)\n",
      "Requirement already satisfied: google-auth in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (1.29.0)\n",
      "Requirement already satisfied: six>=1.9.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth) (1.15.0)\n",
      "Requirement already satisfied: setuptools>=40.3.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth) (50.3.1.post20201107)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth) (0.2.8)\n",
      "Requirement already satisfied: cachetools<5.0,>=2.0.0 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth) (4.2.1)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4; python_version >= \"3.6\" in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from google-auth) (4.7.2)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth) (0.4.8)\n",
      "Requirement already satisfied: google-api-python-client in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (2.6.0)\n",
      "Requirement already satisfied: google-auth-httplib2 in /Users/jonas/opt/anaconda3/lib/python3.8/site-packages (0.1.0)\n",
      "\u001b[31mERROR: Could not find a version that satisfies the requirement google-auth-oauthlibfrom (from versions: none)\u001b[0m\n",
      "\u001b[31mERROR: No matching distribution found for google-auth-oauthlibfrom\u001b[0m\n",
      "Your browser has been opened to visit:\n",
      "\n",
      "    https://accounts.google.com/o/oauth2/auth?client_id=610714584938-1it1pegtlnsvoov8eebtrokd7on6t0j0.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code\n",
      "\n",
      "Authentication successful.\n"
     ]
    }
   ],
   "source": [
    "!pip install Google-Images-Search\n",
    "!pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib\n",
    "!pip install pydrive\n",
    "!pip install google-auth\n",
    "from pydrive.auth import GoogleAuth\n",
    "!pip install google-api-python-client google-auth-httplib2 google-auth-oauthlibfrom pydrive.auth\n",
    "from pydrive.drive import GoogleDrive\n",
    "import os\n",
    "g_login = GoogleAuth()\n",
    "g_login.LocalWebserverAuth()\n",
    "drive = GoogleDrive(g_login)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'GoogleAuth' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-2-99c6e5c26f15>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mg_login\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mGoogleAuth\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mg_login\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mLocalWebserverAuth\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mdrive\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mGoogleDrive\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mg_login\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'GoogleAuth' is not defined"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-6:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/grapes(52).jpg'>\n",
      "Exception in thread Thread-17:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/grapes(63).jpg'>\n",
      "Exception in thread Thread-19:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/grapes(65).jpg'>\n",
      "Exception in thread Thread-21:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/grapes(67).jpg'>\n",
      "Exception in thread Thread-23:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/grapes(69).jpg'>\n",
      "Exception in thread Thread-27:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/grapes(73).jpg'>\n",
      "Exception in thread Thread-29:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/grapes(75).jpg'>\n",
      "Exception in thread Thread-31:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/grapes(77).jpg'>\n",
      "Exception in thread Thread-33:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/grapes(79).jpg'>\n",
      "Exception in thread Thread-34:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/grapes(80).jpg'>\n",
      "Exception in thread Thread-53:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/grapes(99).jpg'>\n",
      "Exception in thread Thread-55:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/1280px-Grapes%2C_Dry_Creek_Valley-7698.jpg'>\n",
      "Exception in thread Thread-57:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/R%C3%B3zsak%C5%91_grapes.jpg'>\n",
      "Exception in thread Thread-59:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/Solaris_grapes_in_Chateaux_Luna_vineyard_6.jpg'>\n",
      "Exception in thread Thread-64:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/Keknyelu_grapes.jpg'>\n",
      "Exception in thread Thread-66:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 241, in _download_and_resize\n",
      "    image.resize(width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 437, in resize\n",
      "    self._fetch_resize_save.__class__.resize(self._path, width, height)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/google_images_search/fetch_resize_save.py\", line 329, in resize\n",
      "    img = Image.open(fd_img)\n",
      "  File \"/Users/jonas/opt/anaconda3/lib/python3.8/site-packages/PIL/Image.py\", line 2967, in open\n",
      "    raise UnidentifiedImageError(\n",
      "PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/Users/jonas/Downloads/Screenscraping/grapes/Merlot_Grape.jpg'>\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/jonas/Downloads/Screenscraping/grapes/grapes(99).jpg\n",
      "/Users/jonas/Downloads/Screenscraping/grapes/grapes(76).jpg\n",
      "/Users/jonas/Downloads/Screenscraping/grapes/grapes(21).jpg\n",
      "/Users/jonas/Downloads/Screenscraping/grapes/grapes(37).jpg\n",
      "/Users/jonas/Downloads/Screenscraping/grapes/grapes(60).jpg\n",
      "/Users/jonas/Downloads/Screenscraping/grapes/grapes(3).jpg\n",
      "/Users/jonas/Downloads/Screenscraping/grapes/grapes(95).jpg\n",
      "/Users/jonas/Downloads/Screenscraping/grapes/pexels-photo-5838162.jpg\n",
      "/Users/jonas/Downloads/Screenscraping/grapes/grapes(83).jpg\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-6-9af4a057176c>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     52\u001b[0m                       \u001b[0mfile_drive\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdrive\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mCreateFile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m{\u001b[0m\u001b[0;34m\"title\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mfn\u001b[0m \u001b[0;34m}\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     53\u001b[0m             \u001b[0mfile_drive\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSetContentFile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mf\u001b[0m\u001b[0;34m)\u001b[0m  \u001b[0;31m# Added\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 54\u001b[0;31m             \u001b[0mfile_drive\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mUpload\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     55\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     56\u001b[0m             \u001b[0;32mcontinue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/pydrive/files.py\u001b[0m in \u001b[0;36mUpload\u001b[0;34m(self, param)\u001b[0m\n\u001b[1;32m    283\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_FilesPatch\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mparam\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mparam\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    284\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 285\u001b[0;31m       \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_FilesInsert\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mparam\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mparam\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    286\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    287\u001b[0m   \u001b[0;32mdef\u001b[0m \u001b[0mTrash\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparam\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/pydrive/auth.py\u001b[0m in \u001b[0;36m_decorated\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m     73\u001b[0m       \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhttp\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mauth\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mGet_Http_Object\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     74\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 75\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0mdecoratee\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     76\u001b[0m   \u001b[0;32mreturn\u001b[0m \u001b[0m_decorated\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     77\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/pydrive/files.py\u001b[0m in \u001b[0;36m_FilesInsert\u001b[0;34m(self, param)\u001b[0m\n\u001b[1;32m    366\u001b[0m       \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdirty\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'content'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    367\u001b[0m         \u001b[0mparam\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'media_body'\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_BuildMediaBody\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 368\u001b[0;31m       metadata = self.auth.service.files().insert(**param).execute(\n\u001b[0m\u001b[1;32m    369\u001b[0m         http=self.http)\n\u001b[1;32m    370\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mHttpError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0merror\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/googleapiclient/_helpers.py\u001b[0m in \u001b[0;36mpositional_wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    132\u001b[0m                 \u001b[0;32melif\u001b[0m \u001b[0mpositional_parameters_enforcement\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mPOSITIONAL_WARNING\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    133\u001b[0m                     \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwarning\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmessage\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 134\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mwrapped\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    135\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    136\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mpositional_wrapper\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/googleapiclient/http.py\u001b[0m in \u001b[0;36mexecute\u001b[0;34m(self, http, num_retries)\u001b[0m\n\u001b[1;32m    897\u001b[0m             \u001b[0mbody\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    898\u001b[0m             \u001b[0;32mwhile\u001b[0m \u001b[0mbody\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 899\u001b[0;31m                 \u001b[0m_\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbody\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mnext_chunk\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mhttp\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mhttp\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnum_retries\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mnum_retries\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    900\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mbody\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    901\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/googleapiclient/_helpers.py\u001b[0m in \u001b[0;36mpositional_wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    132\u001b[0m                 \u001b[0;32melif\u001b[0m \u001b[0mpositional_parameters_enforcement\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mPOSITIONAL_WARNING\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    133\u001b[0m                     \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwarning\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmessage\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 134\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mwrapped\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    135\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    136\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mpositional_wrapper\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/googleapiclient/http.py\u001b[0m in \u001b[0;36mnext_chunk\u001b[0;34m(self, http, num_retries)\u001b[0m\n\u001b[1;32m   1075\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1076\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1077\u001b[0;31m                 resp, content = http.request(\n\u001b[0m\u001b[1;32m   1078\u001b[0m                     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mresumable_uri\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmethod\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"PUT\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbody\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mheaders\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mheaders\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1079\u001b[0m                 )\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/oauth2client/transport.py\u001b[0m in \u001b[0;36mnew_request\u001b[0;34m(uri, method, body, headers, redirections, connection_type)\u001b[0m\n\u001b[1;32m    171\u001b[0m             \u001b[0mbody_stream_position\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mbody\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtell\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    172\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 173\u001b[0;31m         resp, content = request(orig_request_method, uri, method, body,\n\u001b[0m\u001b[1;32m    174\u001b[0m                                 \u001b[0mclean_headers\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mheaders\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    175\u001b[0m                                 redirections, connection_type)\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/oauth2client/transport.py\u001b[0m in \u001b[0;36mrequest\u001b[0;34m(http, uri, method, body, headers, redirections, connection_type)\u001b[0m\n\u001b[1;32m    278\u001b[0m     \u001b[0;31m# NOTE: Allowing http or http.request is temporary (See Issue 601).\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    279\u001b[0m     \u001b[0mhttp_callable\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mhttp\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'request'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mhttp\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 280\u001b[0;31m     return http_callable(uri, method=method, body=body, headers=headers,\n\u001b[0m\u001b[1;32m    281\u001b[0m                          \u001b[0mredirections\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mredirections\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    282\u001b[0m                          connection_type=connection_type)\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/httplib2/__init__.py\u001b[0m in \u001b[0;36mrequest\u001b[0;34m(self, uri, method, body, headers, redirections, connection_type)\u001b[0m\n\u001b[1;32m   1706\u001b[0m                     \u001b[0mcontent\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34mb\"\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1707\u001b[0m                 \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1708\u001b[0;31m                     (response, content) = self._request(\n\u001b[0m\u001b[1;32m   1709\u001b[0m                         \u001b[0mconn\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mauthority\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0muri\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest_uri\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmethod\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbody\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mheaders\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mredirections\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcachekey\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1710\u001b[0m                     )\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/httplib2/__init__.py\u001b[0m in \u001b[0;36m_request\u001b[0;34m(self, conn, host, absolute_uri, request_uri, method, body, headers, redirections, cachekey)\u001b[0m\n\u001b[1;32m   1422\u001b[0m             \u001b[0mauth\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest_uri\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mheaders\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbody\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1423\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1424\u001b[0;31m         \u001b[0;34m(\u001b[0m\u001b[0mresponse\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcontent\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_conn_request\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconn\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest_uri\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmethod\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbody\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mheaders\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1425\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1426\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mauth\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/httplib2/__init__.py\u001b[0m in \u001b[0;36m_conn_request\u001b[0;34m(self, conn, request_uri, method, body, headers)\u001b[0m\n\u001b[1;32m   1374\u001b[0m                 \u001b[0;32mpass\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1375\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1376\u001b[0;31m                 \u001b[0mresponse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mconn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetresponse\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1377\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mhttp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclient\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mBadStatusLine\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mhttp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclient\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mResponseNotReady\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1378\u001b[0m                 \u001b[0;31m# If we get a BadStatusLine on the first try then that means\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/http/client.py\u001b[0m in \u001b[0;36mgetresponse\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1345\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1346\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1347\u001b[0;31m                 \u001b[0mresponse\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbegin\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1348\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mConnectionError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1349\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclose\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/http/client.py\u001b[0m in \u001b[0;36mbegin\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    305\u001b[0m         \u001b[0;31m# read until we get a non-100 response\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    306\u001b[0m         \u001b[0;32mwhile\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 307\u001b[0;31m             \u001b[0mversion\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstatus\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mreason\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_read_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    308\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mstatus\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0mCONTINUE\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    309\u001b[0m                 \u001b[0;32mbreak\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/http/client.py\u001b[0m in \u001b[0;36m_read_status\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    266\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    267\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_read_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 268\u001b[0;31m         \u001b[0mline\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreadline\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_MAXLINE\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"iso-8859-1\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    269\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mline\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m>\u001b[0m \u001b[0m_MAXLINE\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    270\u001b[0m             \u001b[0;32mraise\u001b[0m \u001b[0mLineTooLong\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"status line\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/socket.py\u001b[0m in \u001b[0;36mreadinto\u001b[0;34m(self, b)\u001b[0m\n\u001b[1;32m    667\u001b[0m         \u001b[0;32mwhile\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    668\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 669\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_sock\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrecv_into\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    670\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    671\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_timeout_occurred\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/ssl.py\u001b[0m in \u001b[0;36mrecv_into\u001b[0;34m(self, buffer, nbytes, flags)\u001b[0m\n\u001b[1;32m   1239\u001b[0m                   \u001b[0;34m\"non-zero flags not allowed in calls to recv_into() on %s\"\u001b[0m \u001b[0;34m%\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1240\u001b[0m                   self.__class__)\n\u001b[0;32m-> 1241\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnbytes\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbuffer\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1242\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1243\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0msuper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrecv_into\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mbuffer\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnbytes\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mflags\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/ssl.py\u001b[0m in \u001b[0;36mread\u001b[0;34m(self, len, buffer)\u001b[0m\n\u001b[1;32m   1097\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1098\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mbuffer\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1099\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_sslobj\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlen\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbuffer\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1100\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1101\u001b[0m                 \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_sslobj\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlen\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "from google_images_search import GoogleImagesSearch\n",
    "\n",
    "# you can provide API key and CX using arguments,\n",
    "# or you can set environment variables: GCS_DEVELOPER_KEY, GCS_CX\n",
    "GCS_DEVELOPER_KEY = 'AIzaSyC2ohNou98YPmbnkywwOKS93iqM6VfA9vU'\n",
    "GCS_CX = 'picturedownloading'\n",
    "gis = GoogleImagesSearch('AIzaSyC2ohNou98YPmbnkywwOKS93iqM6VfA9vU', '765427faf63e85f02')\n",
    "\n",
    "\n",
    "\n",
    "foods = ['grapes',\n",
    " 'salad',\n",
    " 'lasagna',\n",
    " 'pancakes',\n",
    " 'sushi',\n",
    " 'ramen',\n",
    " 'tacos',\n",
    " 'pizza',\n",
    " 'steak',\n",
    " 'risotto']\n",
    "\n",
    "for food in foods:\n",
    "\n",
    "    # define search params:\n",
    "    _search_params = {\n",
    "        'q': food,\n",
    "        'num': 50,\n",
    "        'safe': 'safeUndefined',\n",
    "        'fileType': 'jpg',\n",
    "        'imgType': 'photo',\n",
    "        'imgSize': 'medium',\n",
    "        'imgDominantColor': 'imgDominantColorUndefined',\n",
    "        'rights': 'cc_publicdomain|cc_attribute|cc_sharealike|cc_noncommercial|cc_nonderived'\n",
    "    }\n",
    "\n",
    "\n",
    "    # this will search, download and resize:\n",
    "    gis.search(search_params=_search_params, path_to_dir=('/Users/jonas/Downloads/Screenscraping/'+food), width=500, height=500, custom_image_name=food)\n",
    "    \n",
    "    # Importing os and glob to find all PDFs inside subfolder\n",
    "    import glob, os\n",
    "\n",
    "    import os\n",
    "\n",
    "    directory = r'/Users/jonas/Downloads/Screenscraping/'+food\n",
    "    for filename in os.listdir(directory):\n",
    "        if filename.endswith(\".jpg\") or filename.endswith(\".png\"):\n",
    "            print(os.path.join(directory, filename))\n",
    "            f = os.path.join(directory, filename)  # Added\n",
    "            with open(f, 'r') as file:  # Modified\n",
    "                      fn = os.path.basename(file.name)\n",
    "                      file_drive = drive.CreateFile({\"title\": fn })\n",
    "            file_drive.SetContentFile(f)  # Added\n",
    "            file_drive.Upload()\n",
    "        else:\n",
    "            continue\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
